spring.application.name=viyom

server.port=8080
server.servlet.context-path=/viyom

spring.datasource.url=jdbc:mysql://localhost:3306/viyom
spring.datasource.username=root
spring.datasource.password=query.java11

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=Rk9mQ0p0Z3hEM3Q1aUpZQm1JQ0pBR2tQbVRXb2hJZW1DQXk=
jwt.expiration=3600000

# Logging levels
logging.level.root=INFO
logging.level.org.springframework=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.viyom.donation.viyom=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Show SQL parameters
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Log request/response
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

# Log SQL statements
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Log transaction management
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.springframework.transaction=DEBUG
